#!/usr/bin/env bash

echo "Start cpplint Code..."

SCRIPT_HOME=$(cd `dirname $0` && pwd)
SOLUTION_HOME=$SCRIPT_HOME
BUILD_HOME=$SOLUTION_HOME/build
SOLUTION_INCLUDE_HOME=$SOLUTION_HOME/include
SOLUTION_SRC_HOME=$SOLUTION_HOME/src
MCKITS_INCLUDE_HOME=$SOLUTION_INCLUDE_HOME/mckits
MCKITS_SRC_HOME=$SOLUTION_SRC_HOME/mckits
MCPPKITS_INCLUDE_HOME=$SOLUTION_INCLUDE_HOME/mcppkits
MCPPKITS_SRC_HOME=$SOLUTION_SRC_HOME/mcppkits

echo "MCPPKITS_SRC_HOME: $MCPPKITS_SRC_HOME"

# cpplint -h 查看帮助文档
# cpplint --recursive dir1 dir2 dir3 ...
cpplint \
  --recursive \
  $MCPPKITS_SRC_HOME
