[language-server.clangd]
command = "clangd"
args = ["--compile-commands-dir=build"]

[[language]]
name = "c"
language-servers = [ "clangd" ]
auto-format = true

[[language]]
name = "cpp"
language-servers = [ "clangd" ]
auto-format = true
